name: bukeet
description: Bukeet

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_keyboard_visibility: ^6.0.0
  flutter_countdown_timer: ^4.1.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1
  webview_flutter: ^4.13.0
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_svg: ^2.2.0
  animate_do: ^4.2.0
  url_launcher: ^6.3.2
  image_fade: ^0.6.2
  pinput: ^5.0.1
  intl: ^0.20.2
  http: ^1.5.0
  get: ^4.7.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
        - asset: assets/fonts/WorkSans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
        - asset: assets/fonts/WorkSans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Black.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Italic.ttf
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Light.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Medium.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-SemiBold.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Bold.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-ExtraBold.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Black.ttf
