name: bukeet
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_keyboard_visibility: ^6.0.0
  flutter_countdown_timer: ^4.1.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  animate_do: ^3.3.4
  image_fade: ^0.6.2
  pinput: ^5.0.0
  intl: ^0.19.0
  get: ^4.6.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/backgrounds/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
        - asset: assets/fonts/WorkSans/WorkSans-SemiBold.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Bold.ttf
        - asset: assets/fonts/WorkSans/WorkSans-ExtraBold.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Black.ttf
        - asset: assets/fonts/WorkSans/WorkSans-Italic.ttf
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Light.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Regular.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Medium.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-SemiBold.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Bold.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-ExtraBold.ttf
        - asset: assets/fonts/LeagueSpartan/LeagueSpartan-Black.ttf
